### ISSUE TITLE
当上传大文件（12MB）时，就卡死了。

### ISSUE THREAD

**Issue by zenbao** [nanbingxyz/5ire#13]
当上传较大 PDF 时，就不动了，一直卡死，不再显示上传进度呢，这个问题会优化吗

**Comment by nanbingxyz** [comment]
@zenbao 请问你是什么操作系统，内存多大？

**Comment by zenbao** [comment]
> @zenbao 请问你是什么操作系统，内存多大？

macOS，内存 16g，2018macbook，老机器了。小文件没问题，大文件前几次都停在 3%，最后一次进度到 21%，可能是机器问题，我很期待这个软件，最好能和 google的 notebook 看齐，他那个可以让 AI 自动解析角度提出一些重要问题和分析。加油！

**Comment by nanbingxyz** [comment]
@zenbao 可能和设备内存占用有关, 我回头检查一下， issue我先关闭了。感谢建议，也正在用 NotebookLM。
