### ISSUE TITLE
[问题]谷歌gemini模型知识库引用显示不正确

### ISSUE THREAD

**Issue by icychick-liu** [nanbingxyz/5ire#15]
测试了openai和gemini查询知识库，gemini的引用结果显示不正确，稳定复现。

![image](https://github.com/user-attachments/assets/29a50da8-d8d2-4d3d-a9e7-38c6d5a414a8)

**Comment by nanbingxyz** [comment]
应该是模型能力的问题，我尝试调整下Prompt。
