### ISSUE TITLE
希望可以自定义MCP server

### ISSUE THREAD

**Issue by zeahoo** [nanbingxyz/5ire#20]

**Comment by nanbingxyz** [comment]
@zeahoo 在 userData 的 5ire 文件夹下（Mac在 ~/Library/Application Support/5ire 下）可以找到 mcp.json 配置文件，如果熟悉 JSON 可以直接修改添加 MCP Server，然后重启应用。 由于目前有些 Servers 存在兼容性（Mac 和 Windows下表现不同）问题，所以并未将添加 Server 作为开放功能。

如果配置错误可以直接删除 mcp.json, 应用会自动重置配置。

**Comment by zeahoo** [comment]
> @zeahoo 在 userData 的 5ire 文件夹下（Mac在 ~/Library/Application Support/5ire 下）可以找到 mcp.json 配置文件，如果熟悉 JSON 可以直接修改添加 MCP Server，然后重启应用。 由于目前有些 Servers 存在兼容性（Mac 和 Windows下表现不同）问题，所以并未将添加 Server 作为开放功能。
> 
> 如果配置错误可以直接删除 mcp.json, 应用会自动重置配置。

感谢回复，我试试
