### ISSUE TITLE
When text is generated, I change the window or add a new chat. The program will be crashed and broken

### ISSUE THREAD

**Issue by PinkR1ver** [nanbingxyz/5ire#8]
As the title says.

**Comment by nanbingxyz** [comment]
@PinkR1ver Windows or Mac ? And which version?

**Comment by PinkR1ver** [comment]
OS: Windows 11
5ire version: 0.8.1

**Comment by nanbingxyz** [comment]
@PinkR1ver Unable to reproduce the issue. Does the app crash when you start a new chat during generation, or after generation is complete? And what model are you using?

**Comment by nanbingxyz** [comment]
@PinkR1ver Still unable to reproduce it. However,I have fixed issue #9 on v0.8.2. I'll close this and recreate it if it happens again.
